version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8501:8501"  # Streamlit default port
    command: streamlit run main.py --server.port=8501 --server.address=0.0.0.0